spring:
  #是否开启spring security基本的鉴权
  security.basic.enabled: true
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/COVID19?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      max-wait-millis: 99999999
    tomcat:
      max-wait: 3000
      min-idle: 5
      max-idle: 30
      max-active: 50
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080
  tomcat:
    connection-timeout: -1

pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
logging:
  config: classpath:logger-config.xml


# JWT
jwt:
  header: jwt-token
  secret: secret
  #token有效期一天(秒)
  expiration: 86400
  token: Authorization
