spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.86.236:3306/COVID19?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: sheng
    password: AINIshiqi081944!
    dbcp2:
      max-wait-millis: 99999999
    tomcat:
      max-wait: 3000
      min-idle: 5
      max-idle: 30
      max-active: 50
server:
  port: 8080